CREATE TABLE IF NOT EXISTS Restaurantdag(
  Id INTEGER NOT NULL,
  Naam TEXT NOT NULL,
  Datum DATE NOT NULL,
  PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS Gerecht(
  Id INTEGER NOT NULL,
  Naam TEXT NOT NULL,
  IsDessert TINYINT(1) NOT NULL,
  Prijs DOUBLE,PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS RestaurantdagGerechten
(
  RestaurantdagId INTEGER NOT NULL,
  GerechtId INTEGER NOT NULL,
  FOREIGN KEY(RestaurantdagId) REFERENCES Restaurantdag(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(GerechtId) REFERENCES Gerecht(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GerechtBestelling
(
  GerechtId INTEGER NOT NULL,
  BestellingsId INTEGER NOT NULL,
  KlantId INTEGER NOT NULL,
  Aantal INTEGER NOT NULL,
  FOREIGN KEY (GerechtId) REFERENCES Gerecht(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (KlantId) REFERENCES Klant(Id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (BestellingsId)
);

CREATE TABLE IF NOT EXISTS Klant
(
  Id INTEGER NOT NULL PRIMARY KEY ,
  Naam TEXT NOT NULL,
  GroepsNaam TEXT,
  BestellingsId INTEGER,
  RestaurantdagId INTEGER NOT NULL,
  FOREIGN KEY (BestellingsId) REFERENCES GerechtBestelling(BestellingsId) ON DELETE CASCADE ON UPDATE CASCADE ,
  FOREIGN KEY (RestaurantdagId) REFERENCES Restaurantdag(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Tijdstip
(
  Id              INTEGER NOT NULL PRIMARY KEY,
  Uur             INTEGER NOT NULL,
  Minuut          INTEGER NOT NULL,
  RestaurantdagId INTEGER NOT NULL,
  FOREIGN KEY (RestaurantdagId) REFERENCES Restaurantdag (Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)